### ISSUE TITLE
Unable to run clap example

### ISSUE THREAD

**Issue by tami5** [bnjjj/twelf#5]
Is it out dated? clap_rs isn't a package I can find. Here what I ran:

main.rs
```rust
use clap::App;
use twelf::{config, Layer};

#[config]
#[derive(Debug)]
struct Config {
    /// Documentation inside clap, to specifiy db_host
    db_host: String,
    threads: usize,
    /// Put in verbose mode
    verbose: bool,
}

// execute `cargo run --example clap -- --help` to display help and
// documentation execute `cargo run --example clap -- --db-host localhost
// --threads 5` to set configuration
fn main() {
    let matches = App::new("test_clap")
        .args(&Config::clap_args())
        .get_matches();
    let config = Config::with_layers(&[
        Layer::Env(Some(String::from("APP_"))),
        Layer::Clap(matches),
    ])
    .unwrap();

    println!("config - {:?}", config);
}

```

Cargo.toml
```toml
[package]
name = "test"
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
[dependencies]
clap = "3.0.0-beta.2"               # A simple to use, efficient, and full-featured Command Line Argument Parser
twelf = "0.1.7"                   # Layered configuration system for Rust applications.

```
